import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertNull

class GenerateNewFeaturesTaskTest {

    @Test
    fun sourceKeyIsRelativeToConfiguredSourceDirectory() {
        assertEquals(
            "dev/sherry/wcs/features/items/system/PowerSaver.kt",
            newFeatureSourceKey(
                path = "app/src/main/java/dev/sherry/wcs/features/items/system/PowerSaver.kt",
                sourcePathspec = "app/src/main/java",
            ),
        )
        assertNull(
            newFeatureSourceKey(
                path = "app/src/test/java/dev/sherry/wcs/PowerSaverTest.kt",
                sourcePathspec = "app/src/main/java",
            ),
        )
    }

    @Test
    fun generatedSourceUsesSourceKeysInsteadOfFeatureIds() {
        assertEquals(
            """// Generated by GenerateNewFeaturesTask. Do not edit manually.
package dev.sherry.wcs.features.core

object NewFeatures {
    const val WINDOW_DAYS: Int = 30

    /** 源文件 key -> 其首次加入仓库的 epoch 秒. */
    val ADDED_AT_BY_SOURCE_KEY: Map<String, Long> = mapOf(
        "dev/sherry/wcs/features/items/system/PowerSaver.kt" to 123L,
    )
}
""",
            renderNewFeaturesSource(
                namespace = "dev.sherry.wcs",
                windowDays = 30,
                entries = listOf(
                    "dev/sherry/wcs/features/items/system/PowerSaver.kt" to 123L,
                ),
            ),
        )
    }
}
